apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: openshift-builds
    app.kubernetes.io/version: v1.1.0
  name: openshift-builds-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-builds-operator
subjects:
- kind: ServiceAccount
  name: openshift-builds-operator
  namespace: openshift-builds
